---
- name: Automate Log Processor Deployment
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Project Dependencies are present
      pip:
        name: docker-compose
        state: present

    - name: Tear down old environment (Clean Slate)
      community.docker.docker_compose:
        project_src: /workspaces/Data-Driven-Log-Processor
        state: absent

    - name: Build and Launch the Stack
      community.docker.docker_compose:
        project_src: /workspaces/Data-Driven-Log-Processor
        build: yes
        state: present
      register: output

    - name: Confirm Deployment
      debug:
        msg: "The Data-Driven Pipeline is officially LIVE!"